#theme = "ananke"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

baseurl       = "https://pdcherry.github.io/"
title         = "Frameshift"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
languageCode  = "en-us"
resourceDir   = "../resources"

ignoreFiles = [ "\\.qmd$", "\\.rmd$", "\\.ipynb$", "\\.py$" ]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true

[languages]
  [languages.en]
    title = "Frameshift"
    weight = 1
    contentDir = "content/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Patrick Cherry"
  favicon = ""
  site_logo = ""
  # description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "mastodon"
url = "https://hachyderm.io/@pcherry"
name2 = "pixelfed"
url2 = "https://pixelfed.social/pcherry"
